services:
  postgresql:
    ports:
      - 127.0.0.1:5432:5432
  mariadb:
    ports:
      - 3306:3306
  panel-cache:
    ports:
      - 6379:6379
  pterodactyl:
    ports:
      - 80:80
  pterodactyl-wings:
    ports:
      - "8080:8080"
      - "2022:2022"
  grafana:
    ports:
      - 3000:3000
  prometheus:
    ports:
      - 9090:9090