networks:
  shared_infra_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
  infra_services_net:
    driver: bridge

volumes:
  registry-data:
    driver: local

services:
  ##################################################################
  # Shared Cloudflare/nginx
  ##################################################################
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: infra-cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    networks:
      - shared_infra_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=cloudflared"
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "1"
          memory: 64M
    restart: always
  nginx:
    image: nginx:alpine
    container_name: infra-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./infra/certs:/etc/letsencrypt/live/bonnybonnybonaktan.xyz:ro
      - ./infra/certs:/etc/letsencrypt/archive/bonnybonnybonaktan.xyz:ro
      - ./infra/certs:/etc/letsencrypt/live/internal.bonnybonnybonaktan.xyz:ro
      - ./infra/certs:/etc/letsencrypt/archive/internal.bonnybonnybonaktan.xyz:ro
    networks:
      - shared_infra_net
      - infra_services_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=nginx"
    depends_on:
      - registry
      - registry-ui
      - cloudflared
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "1"
          memory: 64M
    restart: always

  ##################################################################
  # Docker Image Registry
  ##################################################################
  registry:
    image: registry:2
    container_name: infra-registry
    restart: always
    expose:
      - "5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Docker Registry"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_LOG_LEVEL: info
      REGISTRY_LOG_FORMATTER: json
      REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: "true"
      REGISTRY_HEALTH_STORAGEDRIVER_INTERVAL: 10s
      REGISTRY_HEALTH_STORAGEDRIVER_THRESHOLD: 3
    volumes:
      - registry-data:/var/lib/registry
      - ./infra/registry/auth:/auth:ro
      - ./infra/registry/config.yml:/etc/docker/registry/config.yml:ro
    networks:
      - infra_services_net

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: infra-registry_ui
    restart: always
    expose:
      - "80"
    environment:
      REGISTRY_TITLE: "bonnybonnybonaktan.xyz Registry"
      REGISTRY_URL: https://registry.bonnybonnybonaktan.xyz
      SINGLE_REGISTRY: "true"
      DELETE_IMAGES: "true"
      NGINX_PROXY_PASS_URL: http://registry:5000
    depends_on:
      - registry
    networks:
      - infra_services_net
