- name: Initial Setup
  hosts: home_server
  become: true
  vars:
    TAILSCALE_AUTH_KEY: tskey-auth-k9KfNQ3SS921CNTRL-MHZ4wMUpd9dHjdWQRa9R9dQgZ7fr9TzUR
  tasks:
    - name: Add Docker APT repository
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: "{{ ansible_distribution_release }}"
        components: stable
        signed_by: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Set kernel network parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
      loop:
        - { name: net.ipv4.ip_forward, value: "1" }
        - { name: net.ipv6.conf.all.forwarding, value: "1" }

    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - python3-debian
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - git
        state: present
        update_cache: true

    - name: Setup Tailscale
      ansible.builtin.shell: curl -fsSL https://tailscale.com/install.sh | sh && tailscale up --auth-key={{TAILSCALE_AUTH_KEY}} --force-reauth

    - name: Pull Infrastructure from Remote
      ansible.builtin.git:
        repo: 'https://github.com/bonaktan/Home-Server.git'
        dest: /srv/Home-Server
        version: main
        force: yes
    - name: Deploy Infrastructure 
      community.docker.docker_compose_v2:
        project_src: /srv/Home-Server
        state: present
        pull: always
        build: always
