server {
    include                     conf.d/filters/scanblock.conf; 
    
    listen                      80;
    server_name                 pearl-horizon.bonnybonnybonaktan.xyz;
    
    ssl_certificate             /etc/letsencrypt/live/bonnybonnybonaktan.xyz/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/bonnybonnybonaktan.xyz/privkey.pem;

    root                        /var/www/pearl-horizon.bonnybonnybonaktan.xyz;

    proxy_set_header            Host                $host;
    proxy_set_header            X-Real-IP           $remote_addr;
    proxy_set_header            X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header            X-Forwarded-Proto   $scheme;

    location / {
        limit_req               zone=general_limit burst=20 nodelay;
        try_files               $uri $uri/ /index.html =404;
        expires                 7;
    }
    location /api {
        limit_req               zone=api_limit burst=20 nodelay;
        set $upstream           http://backend:8000/api;

        proxy_connect_timeout   2s;
        proxy_read_timeout      5s;
        proxy_no_cache          1;
        proxy_cache_bypass      1;
        proxy_cache             off;
        proxy_pass              $upstream;

        error_page 502 503 504 = @proxy_down;
    }

    location @proxy_down {
        return 503 "Service temporarily unavailable";
    }
}